import { storage } from "../storage";
import type { InsertBloodSample } from "@shared/schema";

interface BloodSampleSeedData extends InsertBloodSample {
  tags: string[];
}

const bloodSampleData: BloodSampleSeedData[] = [
  // =====================================================
  // VIRUSES
  // =====================================================
  {
    title: "Epstein-Barr Virus (EBV)",
    scientificName: "Human gammaherpesvirus 4",
    commonName: "Mono virus, Kissing disease virus",
    organismType: "virus",
    category: "pathogen",
    description: "Epstein-Barr virus is one of the most common human viruses worldwide. It belongs to the herpesvirus family and is best known for causing infectious mononucleosis (mono). EBV particles appear as icosahedral capsids surrounded by a tegument and lipid envelope.",
    clinicalSignificance: "EBV infection is associated with infectious mononucleosis, Burkitt lymphoma, nasopharyngeal carcinoma, Hodgkin lymphoma, and multiple sclerosis. Over 90% of adults worldwide have been infected. Reactivation can occur during immunosuppression.",
    diagnosticCriteria: "Electron microscopy shows 120-180nm enveloped particles with icosahedral capsid. Characteristic atypical lymphocytes (Downey cells) seen in peripheral blood smears. Positive heterophile antibody test (Monospot) or EBV-specific serology.",
    differentialDiagnosis: "CMV mononucleosis, acute HIV infection, toxoplasmosis, streptococcal pharyngitis, hepatitis A. Morphologically similar to other herpesviruses.",
    magnification: "100,000x",
    stainType: "electron_microscopy",
    sampleType: "buffy coat",
    preparationMethod: "Negative staining with uranyl acetate or phosphotungstic acid",
    morphologyDescription: "Spherical to pleomorphic enveloped virion. Icosahedral nucleocapsid with 162 capsomeres. Tegument layer between capsid and envelope contains viral proteins. Surface glycoprotein spikes visible on envelope.",
    sizeRange: "120-180nm diameter",
    shapeCharacteristics: "Spherical with icosahedral capsid symmetry",
    colorCharacteristics: "Dark electron-dense core with lighter tegument layer under EM",
    associatedConditions: ["Infectious mononucleosis", "Burkitt lymphoma", "Nasopharyngeal carcinoma", "Hodgkin lymphoma", "Post-transplant lymphoproliferative disorder", "Chronic active EBV infection"],
    symptoms: ["Fatigue", "Fever", "Sore throat", "Swollen lymph nodes", "Enlarged spleen", "Liver inflammation", "Skin rash"],
    transmissionRoute: "Saliva (kissing), blood transfusion, organ transplantation",
    prevalence: "Over 90% of adults worldwide are seropositive",
    imageUrl: "/attached_assets/epstein_barr_micrograph_of_viruses_1768592883411.jpg",
    identificationKeywords: ["herpesvirus", "EBV", "mononucleosis", "mono", "atypical lymphocytes", "Downey cells"],
    aiPromptContext: "When analyzing for EBV: Look for atypical lymphocytes (Downey cells) - large lymphocytes with abundant basophilic cytoplasm that molds around adjacent cells. In electron microscopy, EBV appears as enveloped particles 120-180nm with icosahedral capsid.",
    confidenceFactors: "Characteristic atypical lymphocytes with vacuolated cytoplasm, positive serology, clinical presentation of pharyngitis/lymphadenopathy/hepatosplenomegaly",
    sourceCitation: "Fields Virology, 7th Edition; CDC Epstein-Barr Virus Guidelines",
    sourceUrl: "https://worldofviruses.unl.edu/electron-micrograph-of-epstein-barr-virus/",
    isFeatured: true,
    sortOrder: 1,
    tags: ["herpesvirus", "mononucleosis", "lymphoma", "chronic-fatigue", "immunocompromised"]
  },
  {
    title: "Cytomegalovirus (CMV)",
    scientificName: "Human betaherpesvirus 5",
    commonName: "CMV",
    organismType: "virus",
    category: "pathogen",
    description: "Cytomegalovirus is a common herpesvirus that infects most adults. It typically causes no symptoms in healthy individuals but can cause severe disease in immunocompromised patients and congenital infection in newborns.",
    clinicalSignificance: "Leading cause of congenital viral infection. Major opportunistic pathogen in AIDS and transplant patients. CMV retinitis, colitis, pneumonitis, and encephalitis in immunocompromised.",
    diagnosticCriteria: "Large cells with intranuclear 'owl eye' inclusions pathognomonic. EM shows 150-200nm enveloped particles. CMV antigenemia or PCR for rapid diagnosis.",
    differentialDiagnosis: "EBV mononucleosis, toxoplasmosis, other herpesvirus infections",
    magnification: "100,000x",
    stainType: "electron_microscopy",
    sampleType: "buffy coat",
    morphologyDescription: "Largest human herpesvirus. Spherical enveloped virion with dense tegument layer. Icosahedral capsid with characteristically thick envelope.",
    sizeRange: "150-200nm diameter",
    shapeCharacteristics: "Spherical with thick envelope",
    colorCharacteristics: "Dense core with prominent tegument",
    associatedConditions: ["CMV mononucleosis", "Congenital CMV", "CMV retinitis", "CMV colitis", "CMV pneumonitis", "CMV encephalitis"],
    symptoms: ["Fever", "Fatigue", "Muscle aches", "Vision changes", "Diarrhea"],
    transmissionRoute: "Bodily fluids, blood transfusion, organ transplant, vertical transmission",
    prevalence: "50-80% of adults seropositive by age 40",
    identificationKeywords: ["CMV", "cytomegalovirus", "owl eye", "herpesvirus", "congenital"],
    aiPromptContext: "When analyzing for CMV: Look for enlarged cells with basophilic intranuclear inclusions surrounded by clear halo ('owl eye' appearance). In blood, atypical lymphocytes similar to EBV but often with more prominent cytoplasmic granules.",
    confidenceFactors: "Owl eye inclusions in tissue, positive CMV PCR, antigenemia test",
    sourceCitation: "Fields Virology, 7th Edition",
    isFeatured: true,
    sortOrder: 2,
    tags: ["herpesvirus", "congenital", "immunocompromised", "transplant", "retinitis"]
  },
  {
    title: "HIV Viral Particles",
    scientificName: "Human immunodeficiency virus",
    commonName: "HIV, AIDS virus",
    organismType: "virus",
    category: "pathogen",
    description: "HIV is a retrovirus that attacks CD4+ T lymphocytes, causing progressive immune deficiency. Mature virions are spherical with characteristic surface glycoprotein spikes (gp120/gp41).",
    clinicalSignificance: "Causes AIDS when CD4 count drops below 200 cells/μL. Without treatment, leads to opportunistic infections and malignancies. With antiretroviral therapy, HIV becomes a manageable chronic condition.",
    diagnosticCriteria: "Electron microscopy shows 100-120nm enveloped particles with cone-shaped core. Serological testing (ELISA, Western blot) and viral load (RT-PCR) for diagnosis.",
    differentialDiagnosis: "Acute retroviral syndrome mimics EBV mononucleosis, other causes of immunodeficiency",
    magnification: "150,000x",
    stainType: "electron_microscopy",
    sampleType: "plasma",
    morphologyDescription: "Spherical enveloped virion with characteristic cone-shaped (conical) core containing RNA genome. Surface studded with gp120/gp41 glycoprotein spikes. Matrix protein (p17) lines inner envelope.",
    sizeRange: "100-120nm diameter",
    shapeCharacteristics: "Spherical with conical core",
    colorCharacteristics: "Electron-dense cone-shaped core",
    associatedConditions: ["AIDS", "Acute retroviral syndrome", "HIV-associated dementia", "HIV wasting syndrome", "Various opportunistic infections"],
    symptoms: ["Fever", "Lymphadenopathy", "Weight loss", "Night sweats", "Chronic diarrhea", "Opportunistic infections"],
    transmissionRoute: "Sexual contact, blood exposure, vertical transmission",
    prevalence: "~38 million people living with HIV globally",
    identificationKeywords: ["HIV", "AIDS", "retrovirus", "CD4", "lentivirus"],
    aiPromptContext: "When analyzing for HIV effects: Look for decreased CD4+ lymphocytes, inverted CD4/CD8 ratio, thrombocytopenia. Blood film may show atypical lymphocytes during acute infection. EM shows characteristic cone-shaped core.",
    confidenceFactors: "Positive HIV antibody/antigen test, detectable viral load, decreased CD4 count",
    sourceCitation: "Fields Virology, 7th Edition; WHO HIV Guidelines",
    isFeatured: true,
    sortOrder: 3,
    tags: ["retrovirus", "immunodeficiency", "AIDS", "chronic-infection"]
  },

  // =====================================================
  // BACTERIA
  // =====================================================
  {
    title: "Borrelia burgdorferi (Lyme Spirochete)",
    scientificName: "Borrelia burgdorferi sensu lato",
    commonName: "Lyme disease spirochete",
    organismType: "bacteria",
    category: "pathogen",
    description: "Borrelia burgdorferi is a spirochete bacterium transmitted by Ixodes tick bites. It has a characteristic corkscrew shape and demonstrates unique motility in dark-field microscopy. The organism is highly adapted to evade immune responses.",
    clinicalSignificance: "Causes Lyme disease with early localized (erythema migrans), early disseminated (multiple EM, cardiac, neurologic), and late (arthritis, encephalopathy) stages. Can cause chronic symptoms if untreated.",
    diagnosticCriteria: "Dark-field microscopy shows motile spirochetes 10-30μm long. Two-tier serology (ELISA followed by Western blot). PCR of synovial fluid or CSF in appropriate clinical setting.",
    differentialDiagnosis: "Other tick-borne infections (anaplasmosis, babesiosis), viral infections, rheumatoid arthritis, multiple sclerosis",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Helical spirochete with 7-11 flagella bundled at each end. Highly flexible with characteristic corkscrew motility. Outer membrane contains outer surface proteins (Osp) important for immune evasion.",
    sizeRange: "10-30μm length, 0.2-0.3μm width",
    shapeCharacteristics: "Helical/corkscrew with tapered ends",
    colorCharacteristics: "Bright against dark background in dark-field; pink-red with Giemsa stain",
    associatedConditions: ["Lyme disease", "Lyme arthritis", "Lyme carditis", "Neuroborreliosis", "Post-treatment Lyme disease syndrome"],
    symptoms: ["Erythema migrans (bull's eye rash)", "Fever", "Fatigue", "Joint pain", "Facial palsy", "Heart block", "Cognitive difficulties"],
    transmissionRoute: "Ixodes tick bite (deer tick, black-legged tick)",
    prevalence: "~476,000 cases annually in US, endemic in Northeast and Upper Midwest",
    identificationKeywords: ["spirochete", "Lyme", "Borrelia", "tick-borne", "corkscrew"],
    aiPromptContext: "When analyzing for Borrelia: Use dark-field microscopy to visualize motile spirochetes. Look for characteristic corkscrew morphology and undulating motility. In Giemsa-stained blood films, spirochetes may be visible but are often too few to detect directly.",
    confidenceFactors: "Visualization of spirochetes in dark-field, positive two-tier serology, erythema migrans rash, tick exposure history",
    sourceCitation: "Mandell's Principles and Practice of Infectious Diseases",
    isFeatured: true,
    sortOrder: 10,
    tags: ["spirochete", "tick-borne", "Lyme", "arthritis", "neurologic"]
  },
  {
    title: "Staphylococcus aureus in Blood",
    scientificName: "Staphylococcus aureus",
    commonName: "Staph, Golden staph",
    organismType: "bacteria",
    category: "pathogen",
    description: "S. aureus is a gram-positive coccus arranged in grape-like clusters. It is a major cause of bloodstream infections (bacteremia) and can cause serious complications including endocarditis and metastatic infections.",
    clinicalSignificance: "Leading cause of nosocomial and community-acquired bacteremia. MRSA strains resistant to methicillin and other beta-lactams. Associated with high morbidity and mortality, especially with endocarditis.",
    diagnosticCriteria: "Gram stain shows gram-positive cocci in clusters. Blood cultures positive within 24-48 hours. Coagulase-positive. Golden pigment on culture.",
    differentialDiagnosis: "Coagulase-negative staphylococci, other gram-positive cocci",
    magnification: "1000x",
    stainType: "gram_stain",
    sampleType: "whole blood",
    morphologyDescription: "Spherical cocci 0.5-1.5μm diameter arranged in irregular grape-like clusters. Non-motile, non-spore forming. Gram-positive (purple) with thick peptidoglycan cell wall.",
    sizeRange: "0.5-1.5μm diameter",
    shapeCharacteristics: "Spherical cocci in clusters",
    colorCharacteristics: "Purple/blue with Gram stain (gram-positive)",
    associatedConditions: ["Bacteremia", "Endocarditis", "Osteomyelitis", "Septic arthritis", "Skin/soft tissue infections", "Toxic shock syndrome"],
    symptoms: ["Fever", "Chills", "Hypotension", "Tachycardia", "New heart murmur", "Petechiae"],
    transmissionRoute: "Direct contact, healthcare-associated, colonization",
    prevalence: "~120,000 S. aureus bloodstream infections annually in US",
    identificationKeywords: ["staph", "Staphylococcus", "bacteremia", "MRSA", "cocci", "clusters"],
    aiPromptContext: "When analyzing for S. aureus: Look for gram-positive cocci in characteristic cluster arrangement (like grapes). In direct blood examination, organisms may be seen within neutrophils. Associated with toxic granulation and left shift in neutrophils.",
    confidenceFactors: "Gram-positive cocci in clusters, positive blood culture, coagulase positive",
    sourceCitation: "Mandell's Principles and Practice of Infectious Diseases",
    sortOrder: 11,
    tags: ["gram-positive", "bacteremia", "MRSA", "endocarditis", "sepsis"]
  },
  {
    title: "Treponema pallidum (Syphilis Spirochete)",
    scientificName: "Treponema pallidum subspecies pallidum",
    commonName: "Syphilis spirochete",
    organismType: "bacteria",
    category: "pathogen",
    description: "T. pallidum is a slender spirochete that causes syphilis. It cannot be cultured in vitro and is visualized by dark-field microscopy. The organism has characteristic tight, regular coils.",
    clinicalSignificance: "Causes syphilis with primary (chancre), secondary (rash, condyloma lata), latent, and tertiary (gummas, cardiovascular, neurosyphilis) stages. Congenital syphilis remains a major public health concern.",
    diagnosticCriteria: "Dark-field microscopy of chancre exudate shows characteristic spirochetes. Serology: non-treponemal (RPR, VDRL) and treponemal (FTA-ABS, TP-PA) tests.",
    differentialDiagnosis: "Other spirochetal infections, chancroid, herpes simplex, drug reactions",
    magnification: "1000x",
    stainType: "dark_field",
    sampleType: "whole blood",
    morphologyDescription: "Slender spirochete with 6-14 tightly wound regular coils. Characteristic rotational and flexion motility. Cannot be visualized with standard staining due to thinness (<0.2μm).",
    sizeRange: "6-20μm length, 0.1-0.2μm width",
    shapeCharacteristics: "Tightly coiled helix, regular spirals",
    colorCharacteristics: "Bright against dark background in dark-field",
    associatedConditions: ["Primary syphilis", "Secondary syphilis", "Tertiary syphilis", "Neurosyphilis", "Congenital syphilis"],
    symptoms: ["Painless chancre", "Maculopapular rash", "Mucous patches", "Condyloma lata", "Gummas", "Tabes dorsalis"],
    transmissionRoute: "Sexual contact, vertical transmission",
    prevalence: "~130,000 cases annually in US, increasing incidence",
    identificationKeywords: ["spirochete", "syphilis", "Treponema", "STI", "chancre"],
    aiPromptContext: "When analyzing for T. pallidum: Use dark-field microscopy on lesion exudate. Spirochetes are very thin with tight, regular coils and characteristic corkscrew motility. Blood examination during secondary syphilis may show spirochetes but sensitivity is low.",
    confidenceFactors: "Dark-field visualization from lesion, reactive serology, characteristic clinical lesions",
    sourceCitation: "CDC STI Treatment Guidelines 2021",
    sortOrder: 12,
    tags: ["spirochete", "STI", "syphilis", "congenital", "dark-field"]
  },

  // =====================================================
  // PARASITES
  // =====================================================
  {
    title: "Plasmodium falciparum (Malaria Parasite)",
    scientificName: "Plasmodium falciparum",
    commonName: "Malaria parasite, Falciparum malaria",
    organismType: "parasite",
    category: "pathogen",
    description: "P. falciparum is the most dangerous malaria species, responsible for the majority of malaria deaths. It causes severe and potentially fatal malaria with complications including cerebral malaria and severe anemia.",
    clinicalSignificance: "Most lethal malaria species. Causes severe malaria with high parasitemia, cerebral malaria, severe anemia, ARDS, and renal failure. Can be rapidly fatal if untreated. Drug resistance is a major concern.",
    diagnosticCriteria: "Giemsa-stained thick and thin blood films show ring forms with characteristic 'appliqué' position. Multiple infections per RBC common. Gametocytes are banana/crescent-shaped. Rapid diagnostic tests (RDT) detect HRP2 antigen.",
    differentialDiagnosis: "Other Plasmodium species (vivax, ovale, malariae, knowlesi), babesiosis, viral hemorrhagic fevers",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Ring forms: delicate, small rings 1-2μm, often at edge of RBC (appliqué). Multiple ring infections common. Mature trophozoites and schizonts rarely seen in peripheral blood (sequestration). Gametocytes: distinctive banana/crescent shape.",
    sizeRange: "Ring forms 1-2μm, gametocytes 8-14μm",
    shapeCharacteristics: "Delicate rings, banana-shaped gametocytes",
    colorCharacteristics: "Blue cytoplasm, red/purple chromatin with Giemsa",
    associatedConditions: ["Uncomplicated malaria", "Severe malaria", "Cerebral malaria", "Severe anemia", "Placental malaria", "Blackwater fever"],
    symptoms: ["Fever", "Chills", "Rigors", "Headache", "Altered consciousness", "Jaundice", "Dark urine", "Respiratory distress"],
    transmissionRoute: "Anopheles mosquito bite",
    prevalence: "~241 million cases annually worldwide, 627,000 deaths (mostly children in Africa)",
    imageUrl: null,
    identificationKeywords: ["malaria", "Plasmodium", "ring forms", "gametocytes", "falciparum", "parasitemia"],
    aiPromptContext: "When analyzing for P. falciparum: Look for small, delicate ring forms often at RBC periphery (appliqué). Multiple rings per RBC is characteristic. Infected RBCs are NOT enlarged (unlike vivax). Mature stages rarely seen. Crescent/banana-shaped gametocytes are pathognomonic.",
    confidenceFactors: "Characteristic ring morphology, multiple infections per RBC, crescent gametocytes, positive RDT, travel to endemic area",
    sourceCitation: "CDC Malaria Diagnosis Guidelines; WHO Malaria Microscopy Manual",
    isFeatured: true,
    sortOrder: 20,
    tags: ["malaria", "parasitemia", "tropical", "mosquito-borne", "fever"]
  },
  {
    title: "Babesia microti",
    scientificName: "Babesia microti",
    commonName: "Babesiosis parasite",
    organismType: "parasite",
    category: "pathogen",
    description: "Babesia is a tick-transmitted intraerythrocytic parasite that causes babesiosis. It can appear similar to malaria ring forms but has distinguishing features including Maltese cross (tetrad) formations.",
    clinicalSignificance: "Causes babesiosis ranging from asymptomatic to severe hemolytic anemia, especially in asplenic or immunocompromised patients. Co-infection with Lyme disease common. Can be transfusion-transmitted.",
    diagnosticCriteria: "Giemsa-stained blood film shows ring forms and characteristic 'Maltese cross' tetrads. No hemozoin pigment (unlike malaria). PCR and serology confirm diagnosis.",
    differentialDiagnosis: "Plasmodium falciparum, other Babesia species",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Ring forms similar to P. falciparum but more pleomorphic. Characteristic 'Maltese cross' tetrad forms (4 merozoites in cruciform arrangement). No pigment in infected cells. Extracellular parasites may be seen.",
    sizeRange: "1-5μm",
    shapeCharacteristics: "Pleomorphic rings, Maltese cross tetrads",
    colorCharacteristics: "Blue cytoplasm, red chromatin with Giemsa",
    associatedConditions: ["Babesiosis", "Hemolytic anemia", "Asplenia-related severe infection"],
    symptoms: ["Fever", "Chills", "Fatigue", "Hemolytic anemia", "Jaundice", "Dark urine"],
    transmissionRoute: "Ixodes tick bite, blood transfusion",
    prevalence: "Endemic in Northeast and Upper Midwest US",
    identificationKeywords: ["Babesia", "babesiosis", "Maltese cross", "tick-borne", "hemolytic"],
    aiPromptContext: "When analyzing for Babesia: Look for pleomorphic ring forms WITHOUT pigment (differentiates from malaria). Maltese cross (tetrad) formations are pathognomonic but not always present. Multiple infections per RBC common. Consider in febrile patient with tick exposure or recent transfusion.",
    confidenceFactors: "Maltese cross formations, positive PCR, tick exposure history, no travel to malaria-endemic area",
    sourceCitation: "CDC Babesiosis Guidelines",
    sortOrder: 21,
    tags: ["tick-borne", "hemolytic", "transfusion", "Lyme-coinfection"]
  },
  {
    title: "Trypanosoma cruzi (Chagas Disease)",
    scientificName: "Trypanosoma cruzi",
    commonName: "Chagas disease parasite",
    organismType: "parasite",
    category: "pathogen",
    description: "T. cruzi is a flagellated protozoan that causes Chagas disease. Trypomastigotes in blood have a characteristic C or S shape with a large kinetoplast. The parasite invades cardiac and GI tissue.",
    clinicalSignificance: "Causes acute Chagas disease with potential progression to chronic phase with cardiac (cardiomyopathy) and GI (megacolon, megaesophagus) complications. Leading cause of cardiomyopathy in endemic areas.",
    diagnosticCriteria: "Giemsa-stained blood film shows trypomastigotes during acute phase. Large kinetoplast visible at posterior end. Serology for chronic phase. PCR increasingly used.",
    differentialDiagnosis: "Trypanosoma rangeli, other trypanosomes, leishmaniasis",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Trypomastigotes are 15-20μm with slender body, pointed ends, undulating membrane, and flagellum. Large kinetoplast at posterior end (differentiates from T. rangeli). C or S shaped in blood films.",
    sizeRange: "15-20μm length",
    shapeCharacteristics: "C or S shaped, slender with undulating membrane",
    colorCharacteristics: "Blue-purple cytoplasm, red nucleus and kinetoplast with Giemsa",
    associatedConditions: ["Acute Chagas disease", "Chronic Chagas cardiomyopathy", "Megacolon", "Megaesophagus"],
    symptoms: ["Romaña sign", "Chagoma", "Fever", "Lymphadenopathy", "Heart failure", "Arrhythmias", "Dysphagia", "Constipation"],
    transmissionRoute: "Triatomine bug feces, blood transfusion, congenital, oral (contaminated food)",
    prevalence: "6-7 million infected worldwide, mostly Latin America",
    identificationKeywords: ["Chagas", "Trypanosoma", "trypomastigote", "kinetoplast", "cardiomyopathy"],
    aiPromptContext: "When analyzing for T. cruzi: Look for C or S-shaped trypomastigotes with prominent posterior kinetoplast. Parasites are extracellular in blood during acute phase. Chronic phase rarely shows circulating parasites. Consider in patients from endemic areas with cardiomyopathy.",
    confidenceFactors: "Visualization of trypomastigotes with large kinetoplast, positive serology, epidemiologic exposure",
    sourceCitation: "CDC Chagas Disease Guidelines",
    sortOrder: 22,
    tags: ["Chagas", "cardiomyopathy", "trypanosomiasis", "Latin-America", "congenital"]
  },

  // =====================================================
  // BLOOD CELL MORPHOLOGY - ABNORMALITIES
  // =====================================================
  {
    title: "Rouleaux Formation",
    scientificName: null,
    commonName: "Coin stacking, Stacked coins",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Rouleaux formation occurs when red blood cells stack on top of each other like coins due to increased plasma protein concentration. It is commonly seen in multiple myeloma, inflammatory conditions, and paraproteinemias.",
    clinicalSignificance: "Indicates elevated plasma proteins, especially fibrinogen or immunoglobulins. Strong association with multiple myeloma, Waldenström macroglobulinemia, and chronic inflammatory states. Causes elevated ESR.",
    diagnosticCriteria: "Blood film shows RBCs stacked in linear arrays resembling coins. Must distinguish from pseudorouleaux (artifact) by examining multiple fields and thin areas of smear.",
    differentialDiagnosis: "Agglutination (irregular clumps), artifact from thick smear",
    magnification: "400-1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Red blood cells aligned in parallel stacks resembling coins. Stacks may be linear or branching. Individual cells maintain normal biconcave morphology but appear as overlapping discs.",
    sizeRange: "Normal RBC size (6-8μm), stacks variable length",
    shapeCharacteristics: "Linear stacks, coin-like arrangement",
    colorCharacteristics: "Normal RBC staining, pink-red central pallor may be less apparent",
    associatedConditions: ["Multiple myeloma", "Waldenström macroglobulinemia", "Chronic infections", "Autoimmune diseases", "Pregnancy"],
    symptoms: ["Elevated ESR", "Hyperviscosity symptoms", "Bone pain", "Fatigue"],
    transmissionRoute: null,
    prevalence: "Common finding in paraproteinemias",
    identificationKeywords: ["rouleaux", "coin stacking", "myeloma", "paraprotein", "ESR"],
    aiPromptContext: "When analyzing for rouleaux: Look for RBCs stacked in linear arrays like coins. Distinguish from agglutination (irregular clumps) and artifact (check thin areas). Strong indicator of elevated plasma proteins - consider multiple myeloma, macroglobulinemia, or chronic inflammation.",
    confidenceFactors: "Consistent stacking pattern in thin areas of smear, elevated ESR, serum protein electrophoresis abnormality",
    sourceCitation: "Blood: Principles and Practice of Hematology",
    isFeatured: true,
    sortOrder: 30,
    tags: ["myeloma", "hyperviscosity", "ESR", "paraprotein", "morphology"]
  },
  {
    title: "Spherocytes",
    scientificName: null,
    commonName: "Sphere cells",
    organismType: "cell_abnormality",
    category: "morphology",
    description: "Spherocytes are abnormally spherical red blood cells that lack the normal biconcave shape. They result from membrane loss and are characteristic of hereditary spherocytosis and autoimmune hemolytic anemia.",
    clinicalSignificance: "Key finding in hereditary spherocytosis and warm autoimmune hemolytic anemia. Spherocytes are osmotically fragile and prone to splenic destruction, causing hemolysis.",
    diagnosticCriteria: "Small, dense, round RBCs lacking central pallor on blood film. Increased MCHC. Positive osmotic fragility test. Direct antiglobulin test (DAT) positive in autoimmune causes.",
    differentialDiagnosis: "Artifact, dehydrated cells, other hemolytic anemias",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Small, densely staining round cells without central pallor. Smaller diameter than normal RBCs but with normal or increased hemoglobin content (hyperchromic). Surface area to volume ratio decreased.",
    sizeRange: "Smaller than normal RBCs (<6.5μm diameter)",
    shapeCharacteristics: "Spherical, no biconcave shape",
    colorCharacteristics: "Hyperchromic (dark pink/red), no central pallor",
    associatedConditions: ["Hereditary spherocytosis", "Autoimmune hemolytic anemia", "Burns", "Snake envenomation", "Clostridial sepsis"],
    symptoms: ["Jaundice", "Anemia", "Splenomegaly", "Gallstones", "Fatigue"],
    transmissionRoute: null,
    prevalence: "HS affects 1 in 2,000 in Northern European populations",
    identificationKeywords: ["spherocyte", "hemolysis", "spherocytosis", "AIHA", "DAT"],
    aiPromptContext: "When analyzing for spherocytes: Look for small, round, densely staining RBCs WITHOUT central pallor. They appear smaller and darker than normal cells. Consider hereditary spherocytosis (family history) or autoimmune hemolytic anemia (check DAT). Associated with hemolysis markers.",
    confidenceFactors: "Consistent round cells without central pallor, elevated MCHC, positive osmotic fragility, hemolysis markers",
    sourceCitation: "Williams Hematology",
    sortOrder: 31,
    tags: ["hemolysis", "spherocytosis", "AIHA", "hereditary", "splenomegaly"]
  },
  {
    title: "Schistocytes (Fragmented RBCs)",
    scientificName: null,
    commonName: "Helmet cells, Fragment cells",
    organismType: "cell_abnormality",
    category: "morphology",
    description: "Schistocytes are fragmented red blood cells resulting from mechanical damage. They indicate microangiopathic hemolytic anemia and are key diagnostic findings in TTP, HUS, and DIC.",
    clinicalSignificance: "Hallmark of microangiopathic hemolytic anemia (MAHA). Critical finding in TTP (thrombotic thrombocytopenic purpura), HUS (hemolytic uremic syndrome), DIC, and mechanical heart valve hemolysis. Requires urgent evaluation.",
    diagnosticCriteria: "Fragmented RBCs with irregular shapes - helmet cells, triangles, crescents on blood film. Must count >1% schistocytes for significance. Associated with thrombocytopenia and hemolysis markers.",
    differentialDiagnosis: "Artifact, keratocytes, bite cells",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Fragmented RBC pieces with sharp angular edges. Classic forms include helmet cells (half-moon with horns), triangular cells, and small irregular fragments. No central pallor due to small size.",
    sizeRange: "Variable, usually smaller than normal RBCs",
    shapeCharacteristics: "Irregular fragments - helmet, triangle, crescent shapes",
    colorCharacteristics: "Variable staining, often hyperchromic fragments",
    associatedConditions: ["TTP", "HUS", "DIC", "HELLP syndrome", "Mechanical heart valve hemolysis", "Malignant hypertension", "Scleroderma renal crisis"],
    symptoms: ["Fatigue", "Pallor", "Purpura", "Neurologic symptoms", "Renal failure", "Fever"],
    transmissionRoute: null,
    prevalence: "Variable depending on underlying condition",
    identificationKeywords: ["schistocyte", "fragmented", "MAHA", "TTP", "HUS", "DIC", "helmet cell"],
    aiPromptContext: "When analyzing for schistocytes: Look for irregularly fragmented RBCs with sharp edges - helmet cells, triangles, crescents. Count percentage (>1% is significant). If present with thrombocytopenia, consider urgent evaluation for TTP, HUS, or DIC. This is a critical finding requiring immediate clinical attention.",
    confidenceFactors: "Characteristic fragmented morphology, thrombocytopenia, hemolysis markers, clinical context",
    sourceCitation: "Williams Hematology; ISTH DIC Scoring System",
    isFeatured: true,
    sortOrder: 32,
    tags: ["MAHA", "TTP", "HUS", "DIC", "hemolysis", "emergency"]
  },
  {
    title: "Target Cells (Codocytes)",
    scientificName: null,
    commonName: "Mexican hat cells, Bull's eye cells",
    organismType: "blood_cell_morphology",
    category: "morphology",
    description: "Target cells have a central area of hemoglobin surrounded by a pale ring and then an outer ring of hemoglobin, creating a 'bull's eye' or 'target' appearance. They indicate membrane excess relative to cell volume.",
    clinicalSignificance: "Seen in liver disease, thalassemia, hemoglobin C disease, post-splenectomy, and iron deficiency. The underlying cause determines clinical significance.",
    diagnosticCriteria: "Blood film shows RBCs with central density, surrounding pale zone, and peripheral ring of hemoglobin. Best seen in thin areas of smear.",
    differentialDiagnosis: "Artifact from slow drying, stomatocytes",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Thin cells with central hemoglobin condensation creating target or 'Mexican hat' appearance. Three zones visible: central density, pale ring, outer hemoglobin ring. Result of excess membrane relative to cell volume.",
    sizeRange: "Normal or slightly enlarged RBC diameter",
    shapeCharacteristics: "Central dot with surrounding rings (target pattern)",
    colorCharacteristics: "Central pink, pale middle ring, outer pink ring",
    associatedConditions: ["Liver disease", "Obstructive jaundice", "Thalassemia", "Hemoglobin C disease", "Post-splenectomy", "Iron deficiency anemia"],
    symptoms: ["Variable depending on cause", "Anemia symptoms", "Jaundice"],
    transmissionRoute: null,
    prevalence: "Common finding with multiple etiologies",
    identificationKeywords: ["target cell", "codocyte", "liver disease", "thalassemia", "hemoglobin C"],
    aiPromptContext: "When analyzing for target cells: Look for RBCs with central hemoglobin spot, pale middle ring, and outer hemoglobin rim (bull's eye pattern). Distinguish from artifact by checking thin areas. Consider liver disease, thalassemia, hemoglobinopathy, or post-splenectomy based on clinical context.",
    confidenceFactors: "Consistent target pattern in properly prepared thin areas, supporting clinical context",
    sourceCitation: "Blood: Principles and Practice of Hematology",
    sortOrder: 33,
    tags: ["liver-disease", "thalassemia", "hemoglobinopathy", "morphology"]
  },
  {
    title: "Sickle Cells (Drepanocytes)",
    scientificName: null,
    commonName: "Sickle cells, Crescent cells",
    organismType: "cell_abnormality",
    category: "morphology",
    description: "Sickle cells are crescent or sickle-shaped RBCs caused by polymerization of abnormal hemoglobin S under deoxygenated conditions. They are pathognomonic of sickle cell disease.",
    clinicalSignificance: "Diagnostic of sickle cell disease. Sickle cells cause vaso-occlusion leading to pain crises, stroke, acute chest syndrome, and organ damage. Irreversibly sickled cells contribute to chronic hemolysis.",
    diagnosticCriteria: "Blood film shows elongated, crescent-shaped RBCs. More prominent during crisis. Hemoglobin electrophoresis confirms HbS. Target cells and Howell-Jolly bodies also common.",
    differentialDiagnosis: "Artifact, other hemoglobinopathies",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Elongated, crescent or sickle-shaped RBCs with pointed ends. Irreversibly sickled cells (ISCs) remain sickled regardless of oxygenation. Associated findings include target cells, Howell-Jolly bodies, and polychromasia.",
    sizeRange: "Elongated, variable length",
    shapeCharacteristics: "Crescent/sickle shape with pointed ends",
    colorCharacteristics: "Hyperchromic due to cell dehydration",
    associatedConditions: ["Sickle cell disease (HbSS)", "Sickle-hemoglobin C disease (HbSC)", "Sickle-beta thalassemia"],
    symptoms: ["Pain crisis", "Acute chest syndrome", "Stroke", "Splenic sequestration", "Chronic hemolytic anemia", "Priapism"],
    transmissionRoute: null,
    prevalence: "~100,000 affected in US, common in African, Mediterranean, Middle Eastern, and Indian populations",
    identificationKeywords: ["sickle cell", "drepanocyte", "HbS", "vaso-occlusive", "hemoglobinopathy"],
    aiPromptContext: "When analyzing for sickle cells: Look for elongated crescent-shaped RBCs with pointed ends. Irreversibly sickled cells persist even when oxygenated. Associated findings include target cells, Howell-Jolly bodies (functional asplenia), and nucleated RBCs. Critical finding requiring comprehensive sickle cell evaluation.",
    confidenceFactors: "Characteristic sickle morphology, hemoglobin electrophoresis showing HbS, clinical history",
    sourceCitation: "Williams Hematology; ASH Sickle Cell Guidelines",
    isFeatured: true,
    sortOrder: 34,
    tags: ["sickle-cell", "hemoglobinopathy", "vaso-occlusion", "hemolysis", "genetic"]
  },
  {
    title: "Toxic Granulation",
    scientificName: null,
    commonName: "Toxic granules",
    organismType: "blood_cell_morphology",
    category: "immune_response",
    description: "Toxic granulation refers to prominent dark azurophilic granules in neutrophil cytoplasm, indicating rapid neutrophil production during severe infection or inflammation. It is part of the 'toxic changes' seen in bacterial infections.",
    clinicalSignificance: "Indicates severe infection, sepsis, or significant inflammatory state. Other toxic changes include Döhle bodies, cytoplasmic vacuolization, and left shift. Presence suggests serious underlying condition.",
    diagnosticCriteria: "Blood film shows neutrophils with coarse, dark purple-black granules more prominent than normal primary granules. Often accompanied by left shift and other toxic changes.",
    differentialDiagnosis: "Chédiak-Higashi syndrome (giant granules), Alder-Reilly anomaly, staining artifact",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Neutrophils with abnormally prominent, coarse azurophilic granules that stain dark blue-purple. Granules are larger and more numerous than normal. Often seen with Döhle bodies (pale blue cytoplasmic inclusions) and cytoplasmic vacuoles.",
    sizeRange: "Normal neutrophil size (10-15μm)",
    shapeCharacteristics: "Normal neutrophil shape with prominent granules",
    colorCharacteristics: "Dark purple-black coarse granules",
    associatedConditions: ["Bacterial sepsis", "Severe infections", "Burns", "Trauma", "G-CSF therapy"],
    symptoms: ["Fever", "Tachycardia", "Hypotension", "Altered mental status", "Signs of infection source"],
    transmissionRoute: null,
    prevalence: "Common in hospitalized patients with serious infections",
    identificationKeywords: ["toxic granulation", "sepsis", "infection", "neutrophil", "Döhle bodies"],
    aiPromptContext: "When analyzing for toxic granulation: Look for neutrophils with prominent, coarse dark purple granules filling the cytoplasm. Check for associated toxic changes: Döhle bodies (pale blue cytoplasmic patches), vacuolization, and left shift (bands, metamyelocytes). Indicates severe infection or inflammation requiring clinical attention.",
    confidenceFactors: "Consistent toxic changes across multiple neutrophils, clinical evidence of infection, elevated inflammatory markers",
    sourceCitation: "Williams Hematology",
    sortOrder: 35,
    tags: ["sepsis", "infection", "neutrophil", "toxic-changes", "inflammation"]
  },
  {
    title: "Atypical Lymphocytes (Reactive Lymphocytes)",
    scientificName: null,
    commonName: "Downey cells, Virocytes",
    organismType: "blood_cell_morphology",
    category: "immune_response",
    description: "Atypical or reactive lymphocytes are activated T lymphocytes with characteristic morphologic changes. They are classically seen in infectious mononucleosis but occur in various viral infections.",
    clinicalSignificance: "Classic finding in EBV infectious mononucleosis (>10% atypical lymphocytes). Also seen in CMV, HIV, hepatitis, toxoplasmosis, and drug reactions. Indicates immune activation.",
    diagnosticCriteria: "Blood film shows large lymphocytes with abundant basophilic cytoplasm, often with irregular 'scalloped' edges that mold around adjacent cells. Nuclei may be irregular or lobulated.",
    differentialDiagnosis: "Leukemia/lymphoma cells, monocytes, large granular lymphocytes",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Large lymphocytes with abundant basophilic (blue) cytoplasm and irregular cell margins. Cytoplasm often 'molds' around adjacent RBCs (reactive edge). Nucleus may be eccentric, irregular, or lobulated. Chromatin less clumped than normal lymphocyte.",
    sizeRange: "12-20μm (larger than normal lymphocytes)",
    shapeCharacteristics: "Irregular edges, cytoplasmic 'molding'",
    colorCharacteristics: "Basophilic (deep blue) cytoplasm, darker at edges",
    associatedConditions: ["Infectious mononucleosis (EBV)", "CMV infection", "Acute HIV", "Viral hepatitis", "Toxoplasmosis", "Drug hypersensitivity"],
    symptoms: ["Fever", "Sore throat", "Lymphadenopathy", "Hepatosplenomegaly", "Fatigue"],
    transmissionRoute: null,
    prevalence: "Common in adolescent/young adult EBV infection",
    identificationKeywords: ["atypical lymphocyte", "reactive", "Downey cell", "mononucleosis", "EBV"],
    aiPromptContext: "When analyzing for atypical lymphocytes: Look for large lymphocytes with abundant blue cytoplasm and irregular 'scalloped' edges that wrap around adjacent cells. Distinguish from leukemia cells (atypical lymphs are heterogeneous, leukemia cells are uniform). >10% suggests infectious mononucleosis.",
    confidenceFactors: "Heterogeneous population of reactive-appearing lymphocytes, clinical syndrome of pharyngitis/adenopathy, positive monospot or EBV serology",
    sourceCitation: "Williams Hematology; Blood: Principles and Practice of Hematology",
    isFeatured: true,
    sortOrder: 36,
    tags: ["mononucleosis", "EBV", "viral", "lymphocyte", "reactive"]
  },

  // =====================================================
  // ARTIFACTS AND NORMAL FINDINGS
  // =====================================================
  {
    title: "Platelet Clumping (Pseudothrombocytopenia)",
    scientificName: null,
    commonName: "Platelet clumps, Platelet aggregates",
    organismType: "artifact",
    category: "coagulation",
    description: "Platelet clumping is an in vitro artifact where platelets aggregate in EDTA-anticoagulated blood, causing falsely low platelet counts. It is the most common cause of pseudothrombocytopenia.",
    clinicalSignificance: "Causes falsely low automated platelet counts (pseudothrombocytopenia). Important to recognize to avoid unnecessary workup or treatment for thrombocytopenia. Estimated platelet count and blood film review essential.",
    diagnosticCriteria: "Blood film shows platelet clumps, often at feathered edge of smear. Automated count low but estimated count from film is normal. Repeat count in citrate or heparin anticoagulant gives normal result.",
    differentialDiagnosis: "True thrombocytopenia, platelet satellitism",
    magnification: "400-1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Aggregates of platelets ranging from small clusters to large masses. Individual platelets within clumps may still be discernible. Often concentrated at smear edges (feathered zone).",
    sizeRange: "Clumps variable, individual platelets 2-4μm",
    shapeCharacteristics: "Irregular clumps of varying size",
    colorCharacteristics: "Blue-gray platelet color in clumps",
    associatedConditions: ["EDTA-dependent pseudothrombocytopenia", "Cold agglutinins (for platelets)"],
    symptoms: ["None - this is a laboratory artifact"],
    transmissionRoute: null,
    prevalence: "Estimated 0.1-2% of blood samples",
    identificationKeywords: ["platelet clump", "pseudothrombocytopenia", "EDTA", "artifact"],
    aiPromptContext: "When analyzing for platelet clumping: Look for aggregates of platelets, especially at smear edges. If automated platelet count is low but clumps are seen, this indicates pseudothrombocytopenia. Recommend repeating count with citrate tube and blood film review with estimated platelet count.",
    confidenceFactors: "Visible platelet clumps, discrepancy between automated count and estimated count, normal count in citrate",
    sourceCitation: "Clinical Hematology Atlas",
    sortOrder: 40,
    tags: ["artifact", "pseudothrombocytopenia", "EDTA", "platelet"]
  },
  {
    title: "Crenated Red Blood Cells (Echinocytes)",
    scientificName: null,
    commonName: "Burr cells, Crenated cells",
    organismType: "artifact",
    category: "morphology",
    description: "Echinocytes are RBCs with evenly spaced, small projections (spicules) around the cell surface. They can be artifactual (from slow drying, hyperosmolarity) or pathological (uremia, liver disease).",
    clinicalSignificance: "Must distinguish artifact from true pathology. True burr cells seen in uremia, liver disease, post-transfusion. Artifact common in thick smears or old samples. Clinical correlation essential.",
    diagnosticCriteria: "Blood film shows RBCs with 10-30 evenly spaced, blunted spicules. Artifact echinocytes are uniform throughout smear; true burr cells may have associated findings like schistocytes.",
    differentialDiagnosis: "Acanthocytes (irregular spicules), artifact from preparation",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "RBCs with 10-30 small, evenly spaced, blunted spicules distributed uniformly around cell surface. Projections are similar in size and shape. Central pallor usually preserved.",
    sizeRange: "Normal RBC diameter with added spicule length",
    shapeCharacteristics: "Regular, evenly-spaced blunted projections",
    colorCharacteristics: "Normal RBC staining",
    associatedConditions: ["Artifact (most common)", "Uremia", "Liver disease", "Pyruvate kinase deficiency", "Post-transfusion"],
    symptoms: ["None if artifact", "Uremic symptoms if true burr cells"],
    transmissionRoute: null,
    prevalence: "Common artifact, less common as true pathology",
    identificationKeywords: ["echinocyte", "burr cell", "crenated", "uremia", "artifact"],
    aiPromptContext: "When analyzing for echinocytes: Look for RBCs with regular, evenly-spaced blunted projections. If seen uniformly throughout well-prepared smear and patient has uremia or liver disease, may be pathologic. If only in thick areas or poorly prepared smear, likely artifact. Distinguish from acanthocytes (irregular, variable-length spicules).",
    confidenceFactors: "Distribution pattern (artifact vs true), clinical context, associated findings",
    sourceCitation: "Blood: Principles and Practice of Hematology",
    sortOrder: 41,
    tags: ["artifact", "uremia", "liver-disease", "morphology"]
  },
  {
    title: "Normal Red Blood Cell",
    scientificName: null,
    commonName: "Erythrocyte, RBC",
    organismType: "blood_cell_morphology",
    category: "reference_normal",
    description: "Normal mature red blood cells are biconcave discs with central pallor occupying about one-third of the cell diameter. They provide the reference standard for evaluating RBC morphology abnormalities.",
    clinicalSignificance: "Establishing normal RBC morphology is essential for identifying abnormalities. Normal cells have uniform size (7-8μm), shape (biconcave disc), and hemoglobin content (normochromic central pallor).",
    diagnosticCriteria: "Blood film shows biconcave disc-shaped cells 7-8μm in diameter with central pallor occupying approximately one-third of cell diameter. Uniform size and staining (normocytic, normochromic).",
    differentialDiagnosis: "Various RBC abnormalities",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Biconcave disc with smooth round outline. Central pallor due to thin center of biconcave shape. Uniform pink-red color with central clearing. No inclusions or parasites.",
    sizeRange: "7-8μm diameter",
    shapeCharacteristics: "Round, biconcave disc",
    colorCharacteristics: "Pink-red (eosinophilic) with central pallor",
    associatedConditions: ["Normal hematology"],
    symptoms: ["None - reference normal"],
    transmissionRoute: null,
    prevalence: "Normal finding",
    identificationKeywords: ["normal RBC", "erythrocyte", "reference", "normocytic", "normochromic"],
    aiPromptContext: "Reference for normal RBC: 7-8μm diameter biconcave disc with central pallor occupying 1/3 of cell diameter. Uniform pink staining. Use this as baseline when evaluating for abnormalities like microcytosis (smaller), macrocytosis (larger), hypochromia (increased pallor), spherocytosis (no pallor), etc.",
    confidenceFactors: "Uniform population, appropriate size and staining, consistent with clinical normals",
    sourceCitation: "Williams Hematology",
    sortOrder: 50,
    tags: ["reference", "normal", "RBC", "baseline"]
  },
  {
    title: "Normal Neutrophil",
    scientificName: null,
    commonName: "Segmented neutrophil, PMN, Poly",
    organismType: "blood_cell_morphology",
    category: "reference_normal",
    description: "Normal mature neutrophils have 3-5 nuclear lobes connected by thin filaments, with pale pink cytoplasm containing fine granules. They are the most abundant white blood cells and serve as the reference for evaluating granulocyte abnormalities.",
    clinicalSignificance: "Provides baseline for recognizing abnormalities such as left shift (immature forms), hypersegmentation (>5 lobes), toxic changes, and malignant cells. Normal neutrophil function is essential for bacterial defense.",
    diagnosticCriteria: "Blood film shows 10-15μm cells with 3-5 nuclear lobes connected by thin chromatin strands. Cytoplasm pale pink with fine, evenly distributed granules.",
    differentialDiagnosis: "Band neutrophils, hypersegmented neutrophils, toxic changes",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Round cell 10-15μm with segmented nucleus (3-5 lobes connected by thin chromatin strands). Chromatin is coarsely clumped. Cytoplasm pale pink with fine lilac (neutral) granules evenly distributed.",
    sizeRange: "10-15μm diameter",
    shapeCharacteristics: "Round cell with multilobed nucleus",
    colorCharacteristics: "Purple nucleus, pale pink cytoplasm, fine lilac granules",
    associatedConditions: ["Normal hematology"],
    symptoms: ["None - reference normal"],
    transmissionRoute: null,
    prevalence: "50-70% of WBCs in normal adults",
    identificationKeywords: ["neutrophil", "PMN", "granulocyte", "segmented", "normal"],
    aiPromptContext: "Reference for normal neutrophil: 10-15μm cell with 3-5 nuclear lobes, coarse chromatin, pale pink cytoplasm with fine granules. Use as baseline to identify: left shift (bands, metas - fewer lobes), hypersegmentation (>5 lobes, megaloblastic), toxic changes (coarse granules, vacuoles, Döhle bodies).",
    confidenceFactors: "3-5 nuclear lobes, fine granules, no toxic changes",
    sourceCitation: "Williams Hematology",
    sortOrder: 51,
    tags: ["reference", "normal", "neutrophil", "WBC", "baseline"]
  },

  // =====================================================
  // NUTRITIONAL MARKERS
  // =====================================================
  {
    title: "Hypersegmented Neutrophils",
    scientificName: null,
    commonName: "Hyperseg neuts, Megaloblastic neutrophils",
    organismType: "blood_cell_morphology",
    category: "nutritional_marker",
    description: "Hypersegmented neutrophils have more than 5 nuclear lobes (or any neutrophil with 6+ lobes). They are a sensitive marker of megaloblastic anemia due to vitamin B12 or folate deficiency.",
    clinicalSignificance: "Early and sensitive indicator of B12 or folate deficiency, even before macrocytosis develops. Also seen in myelodysplastic syndromes, hereditary hypersegmentation, and certain drugs (hydroxyurea).",
    diagnosticCriteria: "Blood film shows neutrophils with ≥6 nuclear lobes, or >5% of neutrophils with 5 lobes. Often associated with oval macrocytes and macro-ovalocytic anemia.",
    differentialDiagnosis: "Hereditary hypersegmentation (rare), drug-induced (hydroxyurea), myelodysplasia",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Neutrophils with 6 or more nuclear lobes connected by thin chromatin strands. Lobes may be irregularly shaped. Cell size normal or slightly enlarged. Cytoplasm otherwise normal.",
    sizeRange: "10-15μm (may be slightly enlarged)",
    shapeCharacteristics: "Multilobed nucleus (≥6 lobes)",
    colorCharacteristics: "Normal neutrophil staining",
    associatedConditions: ["Vitamin B12 deficiency", "Folate deficiency", "Myelodysplastic syndrome", "Hydroxyurea therapy", "Hereditary hypersegmentation"],
    symptoms: ["Fatigue", "Glossitis", "Neurologic symptoms (B12)", "Macrocytic anemia"],
    transmissionRoute: null,
    prevalence: "Common in megaloblastic anemia",
    identificationKeywords: ["hypersegmented", "megaloblastic", "B12", "folate", "macrocytic"],
    aiPromptContext: "When analyzing for hypersegmented neutrophils: Count nuclear lobes carefully. Any neutrophil with ≥6 lobes is hypersegmented. If >5% of neutrophils have 5 lobes, also significant. This is an early marker of B12/folate deficiency - check for oval macrocytes and elevated MCV.",
    confidenceFactors: "Consistent hypersegmentation, associated macrocytosis, low B12/folate levels",
    sourceCitation: "Williams Hematology",
    isFeatured: true,
    sortOrder: 60,
    tags: ["B12-deficiency", "folate", "megaloblastic", "macrocytic", "nutritional"]
  },
  {
    title: "Hypochromic Microcytic RBCs",
    scientificName: null,
    commonName: "Iron deficiency cells",
    organismType: "blood_cell_morphology",
    category: "nutritional_marker",
    description: "Hypochromic microcytic red blood cells are small cells with expanded central pallor due to reduced hemoglobin content. They are characteristic of iron deficiency anemia and thalassemia.",
    clinicalSignificance: "Key finding in iron deficiency anemia (most common anemia worldwide) and thalassemia. Iron deficiency shows more anisocytosis and poikilocytosis; thalassemia shows more uniform microcytosis with target cells.",
    diagnosticCriteria: "Blood film shows small RBCs (microcytic) with expanded central pallor occupying >1/3 of cell diameter (hypochromic). Low MCV and MCH on CBC. Iron studies distinguish iron deficiency from thalassemia.",
    differentialDiagnosis: "Thalassemia, anemia of chronic disease, sideroblastic anemia, lead poisoning",
    magnification: "1000x",
    stainType: "wright_giemsa",
    sampleType: "whole blood",
    morphologyDescription: "Small RBCs with thin rim of hemoglobin and expanded central pallor. Often associated with anisocytosis (variable size), poikilocytosis (abnormal shapes), and pencil cells (elongated elliptocytes) in iron deficiency.",
    sizeRange: "<7μm diameter (microcytic)",
    shapeCharacteristics: "Small with expanded central pallor",
    colorCharacteristics: "Pale (hypochromic) with thin pink rim",
    associatedConditions: ["Iron deficiency anemia", "Thalassemia", "Chronic disease", "Lead poisoning", "Sideroblastic anemia"],
    symptoms: ["Fatigue", "Pallor", "Shortness of breath", "Pica", "Koilonychia", "Angular cheilitis"],
    transmissionRoute: null,
    prevalence: "Iron deficiency affects ~2 billion people worldwide",
    identificationKeywords: ["hypochromic", "microcytic", "iron deficiency", "thalassemia", "anemia"],
    aiPromptContext: "When analyzing for hypochromic microcytic cells: Look for small RBCs with expanded central pallor (>1/3 of cell). In iron deficiency, expect variable cell size (anisocytosis), pencil cells, and occasional target cells. In thalassemia, cells are more uniformly small with prominent target cells and basophilic stippling.",
    confidenceFactors: "Consistent hypochromia and microcytosis, low MCV/MCH, iron studies results",
    sourceCitation: "Williams Hematology",
    sortOrder: 61,
    tags: ["iron-deficiency", "thalassemia", "microcytic", "hypochromic", "anemia"]
  }
];

export async function seedBloodSamples(): Promise<void> {
  console.log("Starting blood sample library seeding...");
  
  for (const sampleData of bloodSampleData) {
    try {
      const { tags, ...sample } = sampleData;
      
      const createdSample = await storage.createBloodSample(sample);
      console.log(`Created blood sample: ${createdSample.title}`);
      
      for (const tag of tags) {
        await storage.addBloodSampleTag({
          sampleId: createdSample.id,
          tag: tag,
          tagCategory: null
        });
      }
      console.log(`  Added ${tags.length} tags`);
      
    } catch (error: any) {
      if (error.code === '23505') {
        console.log(`Sample already exists: ${sampleData.title}`);
      } else {
        console.error(`Error creating sample ${sampleData.title}:`, error.message);
      }
    }
  }
  
  console.log("Blood sample library seeding complete!");
}
