import { db } from "../db";
import { trainingTracks, trainingModules, trackModules, quizzes, quizQuestions, quizAnswers, moduleQuizzes } from "@shared/schema";

export const ecsTrainingTracks = [
  {
    id: "ecs-foundations",
    title: "ECS Foundations",
    slug: "ecs-foundations",
    description: "Master the fundamentals of the Endocannabinoid System - the body's master regulatory system. Perfect for beginners and health enthusiasts.",
    imageUrl: "https://drive.google.com/uc?id=1ABC123",
    totalModules: 5,
    estimatedDuration: "8 hours",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: false,
  },
  {
    id: "ecs-practitioner",
    title: "ECS Practitioner Certification",
    slug: "ecs-practitioner",
    description: "Comprehensive certification program for healthcare practitioners. Learn clinical applications, patient assessment, and treatment protocols.",
    imageUrl: "https://drive.google.com/uc?id=1DEF456",
    totalModules: 8,
    estimatedDuration: "24 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
  },
  {
    id: "ecs-advanced-specialist",
    title: "Advanced ECS Specialist",
    slug: "ecs-advanced-specialist",
    description: "Expert-level training for specialists. Deep dive into research, complex conditions, compounding, and cutting-edge therapies.",
    imageUrl: "https://drive.google.com/uc?id=1GHI789",
    totalModules: 6,
    estimatedDuration: "40 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
  },
  {
    id: "site-training-new-staff",
    title: "New Staff Onboarding",
    slug: "site-training-new-staff",
    description: "Essential training for new team members. Learn our platform, products, protocols, and company culture.",
    imageUrl: "https://drive.google.com/uc?id=1JKL012",
    totalModules: 6,
    estimatedDuration: "4 hours",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
  },
  {
    id: "site-training-doctors",
    title: "Doctor Onboarding Program",
    slug: "site-training-doctors",
    description: "Complete orientation for network physicians. Portal navigation, patient management, prescribing protocols, and compliance.",
    imageUrl: "https://drive.google.com/uc?id=1MNO345",
    totalModules: 8,
    estimatedDuration: "6 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
  },
];

export const ecsTrainingModules = [
  // ========== ECS FOUNDATIONS TRACK (Beginner) ==========
  {
    id: "ecs-101-discovery",
    title: "The Discovery of the ECS",
    slug: "ecs-101-discovery",
    description: "Learn about the groundbreaking discovery of the Endocannabinoid System in the 1990s and why it's called the body's master regulatory system.",
    category: "ECS Foundations",
    sortOrder: 1,
    duration: "90 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: false,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_ECS_DISCOVERY",
    imageUrl: "https://drive.google.com/uc?id=1IMG_ECS_DISCOVERY",
  },
  {
    id: "ecs-102-receptors",
    title: "CB1 and CB2 Receptors",
    slug: "ecs-102-receptors",
    description: "Explore the two main cannabinoid receptors - where they're located, what they regulate, and how they communicate with cells.",
    category: "ECS Foundations",
    sortOrder: 2,
    duration: "75 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: false,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_RECEPTORS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_RECEPTORS",
  },
  {
    id: "ecs-103-endocannabinoids",
    title: "Your Body's Own Cannabinoids",
    slug: "ecs-103-endocannabinoids",
    description: "Discover anandamide and 2-AG - the two primary endocannabinoids your body naturally produces and their critical roles in health.",
    category: "ECS Foundations",
    sortOrder: 3,
    duration: "60 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: false,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_ENDOCANNABINOIDS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_ENDOCANNABINOIDS",
  },
  {
    id: "ecs-104-deficiency",
    title: "Clinical Endocannabinoid Deficiency",
    slug: "ecs-104-deficiency",
    description: "Understand CECD - when the ECS is underactive - and its connection to conditions like fibromyalgia, migraines, and IBS.",
    category: "ECS Foundations",
    sortOrder: 4,
    duration: "90 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_CECD",
    imageUrl: "https://drive.google.com/uc?id=1IMG_CECD",
  },
  {
    id: "ecs-105-support",
    title: "Natural ECS Support Strategies",
    slug: "ecs-105-support",
    description: "Learn lifestyle, nutrition, and supplementation strategies to naturally support and optimize your Endocannabinoid System.",
    category: "ECS Foundations",
    sortOrder: 5,
    duration: "75 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_SUPPORT",
    imageUrl: "https://drive.google.com/uc?id=1IMG_SUPPORT",
  },

  // ========== ECS PRACTITIONER CERTIFICATION (Intermediate) ==========
  {
    id: "ecs-201-neuroanatomy",
    title: "ECS Neuroanatomy Deep Dive",
    slug: "ecs-201-neuroanatomy",
    description: "Advanced exploration of ECS distribution in the brain and nervous system. Understand how cannabinoids modulate neurotransmission.",
    category: "ECS Practitioner",
    sortOrder: 1,
    duration: "3 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_NEURO",
    imageUrl: "https://drive.google.com/uc?id=1IMG_NEURO",
  },
  {
    id: "ecs-202-immune-system",
    title: "ECS and Immune Regulation",
    slug: "ecs-202-immune-system",
    description: "How the ECS modulates immune response, inflammation, and autoimmunity. Clinical implications for practitioners.",
    category: "ECS Practitioner",
    sortOrder: 2,
    duration: "3 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_IMMUNE",
    imageUrl: "https://drive.google.com/uc?id=1IMG_IMMUNE",
  },
  {
    id: "ecs-203-patient-assessment",
    title: "ECS Patient Assessment Protocol",
    slug: "ecs-203-patient-assessment",
    description: "Learn to assess patient ECS function using questionnaires, symptom patterns, and clinical markers. Includes case studies.",
    category: "ECS Practitioner",
    sortOrder: 3,
    duration: "3 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_ASSESSMENT",
    imageUrl: "https://drive.google.com/uc?id=1IMG_ASSESSMENT",
  },
  {
    id: "ecs-204-phytocannabinoids",
    title: "Phytocannabinoid Pharmacology",
    slug: "ecs-204-phytocannabinoids",
    description: "Comprehensive review of plant-derived cannabinoids - CBD, CBG, CBN, THC, and minor cannabinoids. Mechanisms and clinical applications.",
    category: "ECS Practitioner",
    sortOrder: 4,
    duration: "4 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_PHYTO",
    imageUrl: "https://drive.google.com/uc?id=1IMG_PHYTO",
  },
  {
    id: "ecs-205-terpenes",
    title: "The Entourage Effect & Terpenes",
    slug: "ecs-205-terpenes",
    description: "How terpenes work synergistically with cannabinoids. Profiles of major terpenes and their therapeutic applications.",
    category: "ECS Practitioner",
    sortOrder: 5,
    duration: "2 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_TERPENES",
    imageUrl: "https://drive.google.com/uc?id=1IMG_TERPENES",
  },
  {
    id: "ecs-206-dosing",
    title: "Dosing Strategies & Titration",
    slug: "ecs-206-dosing",
    description: "Evidence-based dosing protocols for different conditions and patient populations. Start low, go slow methodology.",
    category: "ECS Practitioner",
    sortOrder: 6,
    duration: "3 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_DOSING",
    imageUrl: "https://drive.google.com/uc?id=1IMG_DOSING",
  },
  {
    id: "ecs-207-drug-interactions",
    title: "Drug Interactions & Safety",
    slug: "ecs-207-drug-interactions",
    description: "Critical information on cannabinoid-drug interactions. CYP450 enzyme considerations and contraindications.",
    category: "ECS Practitioner",
    sortOrder: 7,
    duration: "3 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_INTERACTIONS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_INTERACTIONS",
  },
  {
    id: "ecs-208-certification-exam-prep",
    title: "Practitioner Certification Exam",
    slug: "ecs-208-certification-exam-prep",
    description: "Comprehensive exam covering all practitioner modules. Pass with 80% or higher to earn your ECS Practitioner Certification.",
    category: "ECS Practitioner",
    sortOrder: 8,
    duration: "3 hours",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: null,
    imageUrl: "https://drive.google.com/uc?id=1IMG_CERT_EXAM",
  },

  // ========== ADVANCED ECS SPECIALIST (Advanced) ==========
  {
    id: "ecs-301-research-review",
    title: "Critical Research Analysis",
    slug: "ecs-301-research-review",
    description: "How to evaluate cannabinoid research. Understanding study design, statistical significance, and translating research to practice.",
    category: "ECS Advanced",
    sortOrder: 1,
    duration: "6 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_RESEARCH",
    imageUrl: "https://drive.google.com/uc?id=1IMG_RESEARCH",
  },
  {
    id: "ecs-302-complex-conditions",
    title: "ECS in Complex Conditions",
    slug: "ecs-302-complex-conditions",
    description: "Advanced protocols for autoimmune conditions, neurodegenerative diseases, chronic pain syndromes, and mental health disorders.",
    category: "ECS Advanced",
    sortOrder: 2,
    duration: "8 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_COMPLEX",
    imageUrl: "https://drive.google.com/uc?id=1IMG_COMPLEX",
  },
  {
    id: "ecs-303-compounding",
    title: "Cannabinoid Compounding",
    slug: "ecs-303-compounding",
    description: "Advanced formulation strategies. Creating custom cannabinoid preparations for specific patient needs and delivery methods.",
    category: "ECS Advanced",
    sortOrder: 3,
    duration: "6 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_COMPOUNDING",
    imageUrl: "https://drive.google.com/uc?id=1IMG_COMPOUNDING",
  },
  {
    id: "ecs-304-emerging-therapies",
    title: "Emerging Cannabinoid Therapies",
    slug: "ecs-304-emerging-therapies",
    description: "Cutting-edge developments: synthetic cannabinoids, allosteric modulators, enzyme inhibitors, and next-generation formulations.",
    category: "ECS Advanced",
    sortOrder: 4,
    duration: "6 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_EMERGING",
    imageUrl: "https://drive.google.com/uc?id=1IMG_EMERGING",
  },
  {
    id: "ecs-305-case-studies",
    title: "Advanced Clinical Case Studies",
    slug: "ecs-305-case-studies",
    description: "In-depth analysis of complex patient cases. Problem-based learning with peer discussion and expert commentary.",
    category: "ECS Advanced",
    sortOrder: 5,
    duration: "8 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: "https://drive.google.com/file/d/1VIDEO_CASES",
    imageUrl: "https://drive.google.com/uc?id=1IMG_CASES",
  },
  {
    id: "ecs-306-specialist-exam",
    title: "Advanced Specialist Certification Exam",
    slug: "ecs-306-specialist-exam",
    description: "Comprehensive final examination. Includes written exam, case presentation, and oral defense. Pass to earn Advanced ECS Specialist certification.",
    category: "ECS Advanced",
    sortOrder: 6,
    duration: "6 hours",
    difficulty: "advanced" as const,
    isActive: true,
    requiresMembership: true,
    videoUrl: null,
    imageUrl: "https://drive.google.com/uc?id=1IMG_SPECIALIST_EXAM",
  },

  // ========== SITE TRAINING - NEW STAFF ==========
  {
    id: "site-101-welcome",
    title: "Welcome to Forgotten Formula",
    slug: "site-101-welcome",
    description: "Introduction to our mission, values, and the healing ecosystem. Meet the team and understand the ALLIO AI network.",
    category: "Site Training",
    sortOrder: 1,
    duration: "30 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_WELCOME",
    imageUrl: "https://drive.google.com/uc?id=1IMG_WELCOME",
  },
  {
    id: "site-102-platform-nav",
    title: "Platform Navigation",
    slug: "site-102-platform-nav",
    description: "Complete walkthrough of the Allio platform. Learn to navigate dashboards, access resources, and use key features.",
    category: "Site Training",
    sortOrder: 2,
    duration: "45 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_NAV",
    imageUrl: "https://drive.google.com/uc?id=1IMG_NAV",
  },
  {
    id: "site-103-products-overview",
    title: "Product Knowledge Essentials",
    slug: "site-103-products-overview",
    description: "Overview of our product lines: minerals, IV therapies, peptides, bioregulators, and detox protocols. Key benefits and uses.",
    category: "Site Training",
    sortOrder: 3,
    duration: "60 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_PRODUCTS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_PRODUCTS",
  },
  {
    id: "site-104-support-skills",
    title: "Member Support Excellence",
    slug: "site-104-support-skills",
    description: "How to provide exceptional member support. Communication best practices, escalation procedures, and common scenarios.",
    category: "Site Training",
    sortOrder: 4,
    duration: "45 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_SUPPORT_SKILLS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_SUPPORT_SKILLS",
  },
  {
    id: "site-105-compliance",
    title: "PMA Compliance & Legal",
    slug: "site-105-compliance",
    description: "Essential compliance training. Understanding PMA structure, member agreements, and regulatory considerations.",
    category: "Site Training",
    sortOrder: 5,
    duration: "30 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_COMPLIANCE",
    imageUrl: "https://drive.google.com/uc?id=1IMG_COMPLIANCE",
  },
  {
    id: "site-106-new-staff-quiz",
    title: "New Staff Certification Quiz",
    slug: "site-106-new-staff-quiz",
    description: "Comprehensive quiz covering all new staff training modules. Pass with 80% to complete onboarding.",
    category: "Site Training",
    sortOrder: 6,
    duration: "30 min",
    difficulty: "beginner" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor", "clinic"],
    videoUrl: null,
    imageUrl: "https://drive.google.com/uc?id=1IMG_STAFF_QUIZ",
  },

  // ========== SITE TRAINING - DOCTORS ==========
  {
    id: "doc-101-portal-orientation",
    title: "Doctor Portal Orientation",
    slug: "doc-101-portal-orientation",
    description: "Complete walkthrough of the Doctor Portal. Patient management, blood analysis tools, and document generation.",
    category: "Doctor Onboarding",
    sortOrder: 1,
    duration: "45 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_DOC_PORTAL",
    imageUrl: "https://drive.google.com/uc?id=1IMG_DOC_PORTAL",
  },
  {
    id: "doc-102-patient-intake",
    title: "Patient Intake Protocol",
    slug: "doc-102-patient-intake",
    description: "The complete FFPMA 12-system patient intake process. History taking, assessment, and documentation standards.",
    category: "Doctor Onboarding",
    sortOrder: 2,
    duration: "60 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_INTAKE",
    imageUrl: "https://drive.google.com/uc?id=1IMG_INTAKE",
  },
  {
    id: "doc-103-lba-basics",
    title: "Live Blood Analysis Overview",
    slug: "doc-103-lba-basics",
    description: "Introduction to Live Blood Analysis for doctors. Ordering, interpreting results, and using AI analysis tools.",
    category: "Doctor Onboarding",
    sortOrder: 3,
    duration: "45 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_LBA_BASICS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_LBA_BASICS",
  },
  {
    id: "doc-104-protocol-prescribing",
    title: "Protocol Prescribing Guide",
    slug: "doc-104-protocol-prescribing",
    description: "How to prescribe FFPMA protocols. IV therapy, peptides, supplements, and combination approaches.",
    category: "Doctor Onboarding",
    sortOrder: 4,
    duration: "60 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_PRESCRIBING",
    imageUrl: "https://drive.google.com/uc?id=1IMG_PRESCRIBING",
  },
  {
    id: "doc-105-referral-network",
    title: "Building Your Referral Network",
    slug: "doc-105-referral-network",
    description: "How to leverage the FFPMA network. Member referrals, doctor-to-doctor referrals, and revenue sharing.",
    category: "Doctor Onboarding",
    sortOrder: 5,
    duration: "30 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_REFERRALS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_REFERRALS",
  },
  {
    id: "doc-106-ai-agents",
    title: "Working with ALLIO AI Agents",
    slug: "doc-106-ai-agents",
    description: "How to leverage the multi-agent AI system. HIPPOCRATES, PARACELSUS, and other AI assistants for clinical support.",
    category: "Doctor Onboarding",
    sortOrder: 6,
    duration: "45 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_AI_AGENTS",
    imageUrl: "https://drive.google.com/uc?id=1IMG_AI_AGENTS",
  },
  {
    id: "doc-107-compliance-legal",
    title: "Doctor Compliance & Legal",
    slug: "doc-107-compliance-legal",
    description: "PMA structure and doctor responsibilities. Scope of practice, documentation requirements, and liability protection.",
    category: "Doctor Onboarding",
    sortOrder: 7,
    duration: "45 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: "https://drive.google.com/file/d/1VIDEO_DOC_LEGAL",
    imageUrl: "https://drive.google.com/uc?id=1IMG_DOC_LEGAL",
  },
  {
    id: "doc-108-certification-exam",
    title: "Doctor Certification Exam",
    slug: "doc-108-certification-exam",
    description: "Comprehensive exam covering all doctor onboarding modules. Pass with 85% to be fully credentialed.",
    category: "Doctor Onboarding",
    sortOrder: 8,
    duration: "45 min",
    difficulty: "intermediate" as const,
    isActive: true,
    requiresMembership: true,
    roleAccess: ["admin", "doctor"],
    videoUrl: null,
    imageUrl: "https://drive.google.com/uc?id=1IMG_DOC_EXAM",
  },
];

export const ecsQuizzes = [
  // Foundations track quizzes
  {
    id: "quiz-ecs-101",
    title: "ECS Discovery Quiz",
    slug: "ecs-discovery-quiz",
    description: "Test your understanding of the discovery and importance of the Endocannabinoid System.",
    difficulty: "beginner" as const,
    passingScore: 70,
    timeLimit: 15,
    questionsCount: 10,
    isActive: true,
    requiresMembership: false,
    moduleId: "ecs-101-discovery",
  },
  {
    id: "quiz-ecs-102",
    title: "CB Receptors Quiz",
    slug: "cb-receptors-quiz",
    description: "Test your knowledge of CB1 and CB2 receptor locations, functions, and signaling.",
    difficulty: "beginner" as const,
    passingScore: 70,
    timeLimit: 15,
    questionsCount: 10,
    isActive: true,
    requiresMembership: false,
    moduleId: "ecs-102-receptors",
  },
  {
    id: "quiz-ecs-foundations-final",
    title: "ECS Foundations Certification Exam",
    slug: "ecs-foundations-certification",
    description: "Comprehensive exam covering all ECS Foundations modules. Pass to earn your certificate!",
    difficulty: "beginner" as const,
    passingScore: 80,
    timeLimit: 45,
    questionsCount: 40,
    isActive: true,
    requiresMembership: true,
    trackId: "ecs-foundations",
  },
  // Practitioner track quizzes
  {
    id: "quiz-ecs-practitioner-final",
    title: "ECS Practitioner Certification Exam",
    slug: "ecs-practitioner-certification",
    description: "Comprehensive certification exam for ECS Practitioners. Covers all clinical modules.",
    difficulty: "intermediate" as const,
    passingScore: 80,
    timeLimit: 90,
    questionsCount: 75,
    isActive: true,
    requiresMembership: true,
    trackId: "ecs-practitioner",
  },
  // Advanced specialist quizzes
  {
    id: "quiz-ecs-specialist-final",
    title: "Advanced ECS Specialist Exam",
    slug: "ecs-specialist-certification",
    description: "Expert-level certification exam. Written component of the Advanced ECS Specialist certification.",
    difficulty: "advanced" as const,
    passingScore: 85,
    timeLimit: 120,
    questionsCount: 100,
    isActive: true,
    requiresMembership: true,
    trackId: "ecs-advanced-specialist",
  },
  // Site training quizzes
  {
    id: "quiz-new-staff",
    title: "New Staff Onboarding Quiz",
    slug: "new-staff-onboarding-quiz",
    description: "Complete this quiz to finish your new staff onboarding. Covers platform, products, and procedures.",
    difficulty: "beginner" as const,
    passingScore: 80,
    timeLimit: 30,
    questionsCount: 25,
    isActive: true,
    requiresMembership: true,
    trackId: "site-training-new-staff",
  },
  {
    id: "quiz-doctor-onboarding",
    title: "Doctor Certification Quiz",
    slug: "doctor-certification-quiz",
    description: "Final certification quiz for network physicians. Covers all onboarding modules.",
    difficulty: "intermediate" as const,
    passingScore: 85,
    timeLimit: 45,
    questionsCount: 40,
    isActive: true,
    requiresMembership: true,
    trackId: "site-training-doctors",
  },
];

export const ecsQuizQuestions = [
  // ECS Discovery Quiz Questions
  {
    id: "q-ecs101-1",
    quizId: "quiz-ecs-101",
    questionText: "In what decade was the Endocannabinoid System discovered?",
    questionType: "multiple_choice",
    explanation: "The ECS was discovered in the early 1990s when researchers were investigating how THC affects the body.",
    sortOrder: 1,
    points: 1,
    answers: [
      { id: "a-ecs101-1a", text: "1970s", isCorrect: false },
      { id: "a-ecs101-1b", text: "1980s", isCorrect: false },
      { id: "a-ecs101-1c", text: "1990s", isCorrect: true },
      { id: "a-ecs101-1d", text: "2000s", isCorrect: false },
    ],
  },
  {
    id: "q-ecs101-2",
    quizId: "quiz-ecs-101",
    questionText: "The ECS is often called the body's _____ regulatory system.",
    questionType: "multiple_choice",
    explanation: "The ECS regulates virtually every major body system, earning it the title of 'master' regulatory system.",
    sortOrder: 2,
    points: 1,
    answers: [
      { id: "a-ecs101-2a", text: "Primary", isCorrect: false },
      { id: "a-ecs101-2b", text: "Master", isCorrect: true },
      { id: "a-ecs101-2c", text: "Secondary", isCorrect: false },
      { id: "a-ecs101-2d", text: "Auxiliary", isCorrect: false },
    ],
  },
  {
    id: "q-ecs101-3",
    quizId: "quiz-ecs-101",
    questionText: "What is the primary function of the Endocannabinoid System?",
    questionType: "multiple_choice",
    explanation: "The ECS's primary role is maintaining homeostasis - keeping all body systems in optimal balance.",
    sortOrder: 3,
    points: 1,
    answers: [
      { id: "a-ecs101-3a", text: "Digesting food", isCorrect: false },
      { id: "a-ecs101-3b", text: "Maintaining homeostasis", isCorrect: true },
      { id: "a-ecs101-3c", text: "Producing red blood cells", isCorrect: false },
      { id: "a-ecs101-3d", text: "Filtering blood", isCorrect: false },
    ],
  },
  {
    id: "q-ecs101-4",
    quizId: "quiz-ecs-101",
    questionText: "Which organisms have an Endocannabinoid System?",
    questionType: "multiple_choice",
    explanation: "The ECS is found in all vertebrates, from fish to humans, making it an ancient regulatory system.",
    sortOrder: 4,
    points: 1,
    answers: [
      { id: "a-ecs101-4a", text: "Only humans", isCorrect: false },
      { id: "a-ecs101-4b", text: "Only mammals", isCorrect: false },
      { id: "a-ecs101-4c", text: "All vertebrates", isCorrect: true },
      { id: "a-ecs101-4d", text: "Only primates", isCorrect: false },
    ],
  },
  {
    id: "q-ecs101-5",
    quizId: "quiz-ecs-101",
    questionText: "The word 'endocannabinoid' comes from 'endo' meaning:",
    questionType: "multiple_choice",
    explanation: "'Endo' means 'within' - endocannabinoids are cannabinoids produced within your own body.",
    sortOrder: 5,
    points: 1,
    answers: [
      { id: "a-ecs101-5a", text: "Plant-derived", isCorrect: false },
      { id: "a-ecs101-5b", text: "External", isCorrect: false },
      { id: "a-ecs101-5c", text: "Within/Internal", isCorrect: true },
      { id: "a-ecs101-5d", text: "Synthetic", isCorrect: false },
    ],
  },
  // CB Receptors Quiz Questions
  {
    id: "q-ecs102-1",
    quizId: "quiz-ecs-102",
    questionText: "Where are CB1 receptors most highly concentrated?",
    questionType: "multiple_choice",
    explanation: "CB1 receptors are most abundant in the brain and central nervous system.",
    sortOrder: 1,
    points: 1,
    answers: [
      { id: "a-ecs102-1a", text: "Immune cells", isCorrect: false },
      { id: "a-ecs102-1b", text: "Brain and central nervous system", isCorrect: true },
      { id: "a-ecs102-1c", text: "Bones", isCorrect: false },
      { id: "a-ecs102-1d", text: "Skin only", isCorrect: false },
    ],
  },
  {
    id: "q-ecs102-2",
    quizId: "quiz-ecs-102",
    questionText: "CB2 receptors are primarily associated with which system?",
    questionType: "multiple_choice",
    explanation: "CB2 receptors are most abundant in the immune system and peripheral tissues.",
    sortOrder: 2,
    points: 1,
    answers: [
      { id: "a-ecs102-2a", text: "Nervous system", isCorrect: false },
      { id: "a-ecs102-2b", text: "Immune system", isCorrect: true },
      { id: "a-ecs102-2c", text: "Digestive system only", isCorrect: false },
      { id: "a-ecs102-2d", text: "Cardiovascular system only", isCorrect: false },
    ],
  },
  {
    id: "q-ecs102-3",
    quizId: "quiz-ecs-102",
    questionText: "Which functions are regulated by CB1 receptor activation?",
    questionType: "multiple_choice",
    explanation: "CB1 receptors regulate pain, mood, memory, and appetite among other functions.",
    sortOrder: 3,
    points: 1,
    answers: [
      { id: "a-ecs102-3a", text: "Pain, mood, memory, appetite", isCorrect: true },
      { id: "a-ecs102-3b", text: "Bone density only", isCorrect: false },
      { id: "a-ecs102-3c", text: "Hair growth", isCorrect: false },
      { id: "a-ecs102-3d", text: "Nail strength", isCorrect: false },
    ],
  },
  {
    id: "q-ecs102-4",
    quizId: "quiz-ecs-102",
    questionText: "What happens when CB2 receptors are activated?",
    questionType: "multiple_choice",
    explanation: "CB2 activation helps modulate immune response and reduce inflammation.",
    sortOrder: 4,
    points: 1,
    answers: [
      { id: "a-ecs102-4a", text: "Increased heart rate", isCorrect: false },
      { id: "a-ecs102-4b", text: "Immune modulation and reduced inflammation", isCorrect: true },
      { id: "a-ecs102-4c", text: "Enhanced vision", isCorrect: false },
      { id: "a-ecs102-4d", text: "Increased sweating", isCorrect: false },
    ],
  },
  {
    id: "q-ecs102-5",
    quizId: "quiz-ecs-102",
    questionText: "Cannabinoid receptors are a type of:",
    questionType: "multiple_choice",
    explanation: "CB1 and CB2 are G protein-coupled receptors (GPCRs), the largest family of membrane receptors.",
    sortOrder: 5,
    points: 1,
    answers: [
      { id: "a-ecs102-5a", text: "Ion channel receptor", isCorrect: false },
      { id: "a-ecs102-5b", text: "Enzyme receptor", isCorrect: false },
      { id: "a-ecs102-5c", text: "G protein-coupled receptor (GPCR)", isCorrect: true },
      { id: "a-ecs102-5d", text: "Nuclear receptor", isCorrect: false },
    ],
  },
];

export async function seedECSTraining() {
  console.log("[Seed] Starting ECS training data seed...");

  try {
    // Seed training tracks
    console.log("[Seed] Inserting training tracks...");
    for (const track of ecsTrainingTracks) {
      await db.insert(trainingTracks).values(track).onConflictDoNothing();
    }
    console.log(`[Seed] Inserted ${ecsTrainingTracks.length} training tracks`);

    // Seed training modules
    console.log("[Seed] Inserting training modules...");
    for (const module of ecsTrainingModules) {
      const { videoUrl, imageUrl, ...moduleData } = module;
      await db.insert(trainingModules).values({
        ...moduleData,
        imageUrl,
      }).onConflictDoNothing();
    }
    console.log(`[Seed] Inserted ${ecsTrainingModules.length} training modules`);

    // Link modules to tracks
    console.log("[Seed] Linking modules to tracks...");
    const trackModuleLinks = [
      // ECS Foundations
      { trackId: "ecs-foundations", moduleId: "ecs-101-discovery", sortOrder: 1 },
      { trackId: "ecs-foundations", moduleId: "ecs-102-receptors", sortOrder: 2 },
      { trackId: "ecs-foundations", moduleId: "ecs-103-endocannabinoids", sortOrder: 3 },
      { trackId: "ecs-foundations", moduleId: "ecs-104-deficiency", sortOrder: 4 },
      { trackId: "ecs-foundations", moduleId: "ecs-105-support", sortOrder: 5 },
      // ECS Practitioner
      { trackId: "ecs-practitioner", moduleId: "ecs-201-neuroanatomy", sortOrder: 1 },
      { trackId: "ecs-practitioner", moduleId: "ecs-202-immune-system", sortOrder: 2 },
      { trackId: "ecs-practitioner", moduleId: "ecs-203-patient-assessment", sortOrder: 3 },
      { trackId: "ecs-practitioner", moduleId: "ecs-204-phytocannabinoids", sortOrder: 4 },
      { trackId: "ecs-practitioner", moduleId: "ecs-205-terpenes", sortOrder: 5 },
      { trackId: "ecs-practitioner", moduleId: "ecs-206-dosing", sortOrder: 6 },
      { trackId: "ecs-practitioner", moduleId: "ecs-207-drug-interactions", sortOrder: 7 },
      { trackId: "ecs-practitioner", moduleId: "ecs-208-certification-exam-prep", sortOrder: 8 },
      // ECS Advanced Specialist
      { trackId: "ecs-advanced-specialist", moduleId: "ecs-301-research-review", sortOrder: 1 },
      { trackId: "ecs-advanced-specialist", moduleId: "ecs-302-complex-conditions", sortOrder: 2 },
      { trackId: "ecs-advanced-specialist", moduleId: "ecs-303-compounding", sortOrder: 3 },
      { trackId: "ecs-advanced-specialist", moduleId: "ecs-304-emerging-therapies", sortOrder: 4 },
      { trackId: "ecs-advanced-specialist", moduleId: "ecs-305-case-studies", sortOrder: 5 },
      { trackId: "ecs-advanced-specialist", moduleId: "ecs-306-specialist-exam", sortOrder: 6 },
      // Site Training - New Staff
      { trackId: "site-training-new-staff", moduleId: "site-101-welcome", sortOrder: 1 },
      { trackId: "site-training-new-staff", moduleId: "site-102-platform-nav", sortOrder: 2 },
      { trackId: "site-training-new-staff", moduleId: "site-103-products-overview", sortOrder: 3 },
      { trackId: "site-training-new-staff", moduleId: "site-104-support-skills", sortOrder: 4 },
      { trackId: "site-training-new-staff", moduleId: "site-105-compliance", sortOrder: 5 },
      { trackId: "site-training-new-staff", moduleId: "site-106-new-staff-quiz", sortOrder: 6 },
      // Site Training - Doctors
      { trackId: "site-training-doctors", moduleId: "doc-101-portal-orientation", sortOrder: 1 },
      { trackId: "site-training-doctors", moduleId: "doc-102-patient-intake", sortOrder: 2 },
      { trackId: "site-training-doctors", moduleId: "doc-103-lba-basics", sortOrder: 3 },
      { trackId: "site-training-doctors", moduleId: "doc-104-protocol-prescribing", sortOrder: 4 },
      { trackId: "site-training-doctors", moduleId: "doc-105-referral-network", sortOrder: 5 },
      { trackId: "site-training-doctors", moduleId: "doc-106-ai-agents", sortOrder: 6 },
      { trackId: "site-training-doctors", moduleId: "doc-107-compliance-legal", sortOrder: 7 },
      { trackId: "site-training-doctors", moduleId: "doc-108-certification-exam", sortOrder: 8 },
    ];

    for (const link of trackModuleLinks) {
      await db.insert(trackModules).values({
        id: `tm-${link.trackId}-${link.moduleId}`,
        ...link,
        isRequired: true,
      }).onConflictDoNothing();
    }
    console.log(`[Seed] Linked ${trackModuleLinks.length} track-module relationships`);

    // Seed quizzes
    console.log("[Seed] Inserting quizzes...");
    for (const quiz of ecsQuizzes) {
      const { moduleId, trackId, ...quizData } = quiz;
      await db.insert(quizzes).values(quizData).onConflictDoNothing();
      
      // Link quiz to module if applicable
      if (moduleId) {
        await db.insert(moduleQuizzes).values({
          id: `mq-${moduleId}-${quiz.id}`,
          moduleId,
          quizId: quiz.id,
          sortOrder: 1,
          isRequired: true,
        }).onConflictDoNothing();
      }
    }
    console.log(`[Seed] Inserted ${ecsQuizzes.length} quizzes`);

    // Seed quiz questions and answers
    console.log("[Seed] Inserting quiz questions and answers...");
    for (const question of ecsQuizQuestions) {
      const { answers, ...questionData } = question;
      await db.insert(quizQuestions).values(questionData).onConflictDoNothing();
      
      for (const answer of answers) {
        await db.insert(quizAnswers).values({
          id: answer.id,
          questionId: question.id,
          answerText: answer.text,
          isCorrect: answer.isCorrect,
          sortOrder: answers.indexOf(answer) + 1,
        }).onConflictDoNothing();
      }
    }
    console.log(`[Seed] Inserted ${ecsQuizQuestions.length} questions with answers`);

    console.log("[Seed] ECS training seed completed successfully!");
    return { success: true, message: "ECS training data seeded successfully" };
  } catch (error: any) {
    console.error("[Seed] Error seeding ECS training:", error);
    return { success: false, error: error.message };
  }
}
